### ISSUE TITLE
403 Forbidden ("GET / HTTP/1.1" 403 - // "GET /favicon.ico HTTP/1.1" 403 -) Error.

### ISSUE THREAD

**Issue by taurzh** [MizaGBF/WiihUb#2]
Hello, so i'm getting this error message in CMD when i try to enter the server from my Wii U.

```
172.16.0.25 - - [12/Jul/2023 00:56:38] "GET / HTTP/1.1" 403 - 
172.16.0.25 - - [12/Jul/2023 00:56:38] "GET /favicon.ico HTTP/1.1" 403 -
```

And it shows me a 403 Forbidden page in the browser.

Is there something i can do, or did i do something wrong?

![403](https://github.com/MizaGBF/WiihUb/assets/139309788/18a2f994-7970-4e5c-915c-735245a4583e)
![4O3](https://github.com/MizaGBF/WiihUb/assets/139309788/8aafcb9d-8b0c-49e4-8035-a8580d5e9a51)

**Comment by MizaGBF** [comment]
Edit the key "home_network" with the first three numbers of your network ip in config.json.
```
"home_network": "172.16.0",
```
and it should work.
